name: mmtweb
description: "Flutter Website for MomMadeThis."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Kalnia
      fonts:
        - asset: assets/fonts/Kalnia-VariableFont_wdth,wght.ttf
  uses-material-design: true

